pipewire: add missing header for libc++
In file included from src/modules/privacy/privacy.cpp:1:
In file included from include/modules/privacy/privacy.hpp:10:
include/util/pipewire/pipewire_backend.hpp:30:8: error: no template named 'unordered_map' in namespace 'std'
  std::unordered_map<uint32_t, PrivacyNodeInfo*> privacy_nodes;
  ~~~~~^