CI: switch FreeBSD to /quarterly packages
devel/libffi on /latest was recently updated to 3.3, breaking ABI.
However, TravisCI has lang/python37 preinstalled likely from /quarterly.
Instead of calling `pkg upgrade -y` or `pkg upgrade -y python37` switch to
/quarterly until a newer dependency is required to justify /latest.

$ meson build -Dman-pages=enabled
[...]
ImportError: Shared object "libffi.so.6" not found, required by "_ctypes.so"